### ISSUE TITLE
(Fabric) Create train conductors are not protected against taking off train schedule

### ISSUE THREAD

**Issue by Noire86** [thexaero/open-parties-and-claims#487]
Hello! When Create trains are inside the protected chunk - any player may take off the conductors' train schedule, actually ruining the set up train scheme.

Steps to reproduce:

- Build a train on tracks with station. Make train to a contraption
- Place a seat near train control and set a conductor (any animal or Steam And Rails Conductor) to this seat with a leash.
- Claim server chunks
- Check that you cannot interact with blocks or entities in these server claimed chunks.
- Set a train schedule on to a conductor with Right Click of a mouse. It is unprotected.
- Take the schedule back. It is unprotected.

Key notes: 
- Conductor entity is protected from dealing damage to it.
- You can override the Train Station schedule by throwing a Schedule item right onto Train Station block. It lands on its upper side, and overrides current train conductor schedule. I guess this may be fixed with item throwing prohibition?
- When a Blaze Burner is used as a conductor - it is actually protected from the removal of train schedule. But I guess the reason behind that is than the Blaze Burner is actually a Block Entity, rather than a living Entity.

Thanks in advance!

**Comment by thexaero** [comment]
Thanks for reporting!

**Comment by thexaero** [comment]
So strange how I need to spam click the conductor to reproduce this. Was it the same for you?

**Comment by Noire86** [comment]
Not really, single right-click i s enough to put off the schedule from conductor. Are you sure you are not using Blaze Burner?

**Comment by Noire86** [comment]
I tried to upload a video of bug reproducing, but its sad that Github does not allow to upload video with more than 10mb of weight

**Comment by thexaero** [comment]
For me giving a conductor a schedule only works if I spam right click. Taking it works first try though.

**Comment by thexaero** [comment]
I think it's because I'm currently on 1.18.2. Anyway, I've noticed that there is just so much weird stuff going on with the forge event EntityInteractSpecific that they're using. It's absolutely broken on 1.18.2. It's not fired correctly, at the wrong time and with the wrong arguments. Looks fixed on newer forge versions, but I haven't tested it yet. What MC version are you using?

**Comment by thexaero** [comment]
Oh, wait, it was fixed on 1.18.2 too. Let me see what I can do with this now.

**Comment by thexaero** [comment]
Alright, seems to be completely fixed when using 40.2.5 or newer on 1.18.2. I'll go check how other MC versions are affected.

**Comment by Noire86** [comment]
I'm using Forge 1.20.1, by the way

**Comment by thexaero** [comment]
From looking at the 1.20.1 code, there should be no issue, but I haven't got to testing it yet.

**Comment by thexaero** [comment]
Alright, entity interaction protection works fine on 1.20.1 too for me. Are you sure the entity you're interacting with doesn't have a non-attack interaction exception? What mob specifically are you using?

**Comment by Noire86** [comment]
You can use any animal, or Steam N Rails conductor guy.

Just seat them in front of train controls, and grant a schedule.

**Comment by thexaero** [comment]
I'm doing that obviously. Who are you yourself using specifically?

**Comment by Noire86** [comment]
Also, grant a bypass for create:contraption_carriage to allow players interact with seats

**Comment by Noire86** [comment]
My bad, it's create:carriage_contraption

**Comment by thexaero** [comment]
Can you please tell me what mob you are using as the conductor?

**Comment by Noire86** [comment]
> I'm doing that obviously. Who are you yourself using specifically?

Personally, I've used parrot and steam n rails guy.

**Comment by thexaero** [comment]
Alright, thanks! Was it a tamed parrot?

**Comment by Noire86** [comment]
P.S: We can talk about details in discord, if you would like

**Comment by Noire86** [comment]
> Alright, thanks! Was it a tamed parrot?

Not really, what I did was spawning a parrot from the egg and linking it with a leash. No taming whatsoever.

**Comment by thexaero** [comment]
I see. Can you please send me the main config file `openpartiesandclaims-server.toml`?
I don't know about Discord. I'd prefer discussing it here in case I need to look up this issue in the future.

**Comment by Noire86** [comment]
> I see. Can you please send me the main config file `openpartiesandclaims-server.toml`? I don't know about Discord. I'd prefer discussing it here in case I need to look up this issue in the future.

No problem!



Speaking about config, here it is: [openpartiesandclaims-server.toml.txt](https://github.com/user-attachments/files/16051376/openpartiesandclaims-server.toml.txt)

**Comment by thexaero** [comment]
Thanks! Don't see any issues with the config. So strange how I was able to reproduce this on 1.18.2 because of a bug that shouldn't exist on 1.20.1. Pretty unexplainable at this point. What Forge version exactly are you using and what Create version exactly?

**Comment by Noire86** [comment]
While I'm collecting the versions info, can you please clarify what's happened on your side?

You are not able to set or take off schedule from the conductor on a claimed chunk?

**Comment by thexaero** [comment]
On my side the protection works perfectly fine. I can only give or take the schedule when I have permission to do so in the claim. The only way to circumvent it for me is to drop the schedule on the station block.

**Comment by Noire86** [comment]
Create: v0.5.1f
Forge: 47.2.20

**Comment by thexaero** [comment]
Thanks, those are my versions too, so this is very strange. I'll have to take another look at this later. Have to go now.

**Comment by Noire86** [comment]
> On my side the protection works perfectly fine. I can only give or take the schedule when I have permission to do so in the claim. The only way to circumvent it for me is to drop the schedule on the station block.

Even if so, after allowing to interact with train contraption - there is still a possibility to take off the schedule from a conductor, or intercept train controls.

P.S Could it be the Arclight core issue? (Please don't hit me with sharp stones for that)

**Comment by thexaero** [comment]
> P.S Could it be the Arclight core issue? (Please don't hit me with sharp stones for that)

Yes, I can now reproduce this when using Arclight. Going to investigate why that is.

**Comment by thexaero** [comment]
Alright, figured it out. They're overwriting a method completely, removing all of my injections. Looks like they're using a better approach in newer versions but I'm not entirely sure it works there either.
Although I'm pretty sure I can now switch to using the Forge event instead of the injections, now that it has been fixed on Forge's end. Hopefully going to fix this issue too.

**Comment by thexaero** [comment]
Yep, seems to fix the issue.

**Comment by Noire86** [comment]
Really, really thank you! That's great news!

**Comment by HLHTHoldWind** [comment]
This issue is still on fabric 1.20.1 version.

I only need to right click the conductor, openpac will pop a [Main hand] red warning, but I still stole the schedule and stop the train.

**Comment by HLHTHoldWind** [comment]
Fabric 0.15.11
Create 0.5.1f
Opac 0.23.2
Opac create 1.6.0

**Comment by thexaero** [comment]
@HLHTHoldWind There's probably an exception enabled for whatever the entity is, e.g. a villager.

**Comment by HLHTHoldWind** [comment]
> @HLHTHoldWind There's probably an exception enabled for whatever the entity is, e.g. a villager. 

Untamed cat is also an exception?

**Comment by HLHTHoldWind** [comment]
> @HLHTHoldWind There's probably an exception enabled for whatever the entity is, e.g. a villager.


I find only the blaze burner has been protected, you can steal schedules from any other conductors

**Comment by thexaero** [comment]
@HLHTHoldWind I don't know what exceptions you have configured. Test if you can interact with mobs in general and test interaction with armor stands.

**Comment by HLHTHoldWind** [comment]
> @HLHTHoldWind I don't know what exceptions you have configured. Test if you can interact with mobs in general and test interaction with armor stands.

No, I can't interact with other mobs that not on the train (and armor stand). like I can't feed sheep in the claim. The only thing I can do in this claim is steal the train schedule from the mob conductor.

**Comment by thexaero** [comment]
@HLHTHoldWind Did you try interacting with other mobs with an empty hand? Conductors are just normal mobs, protected the same way as everything else. There is no reason for them to work differently. Did you actually test after I asked you?

**Comment by HLHTHoldWind** [comment]
> @HLHTHoldWind Did you try interacting with other mobs with an empty hand? Conductors are just normal mobs, protected the same way as everything else. There is no reason for them to work differently. Did you actually test after I asked you?

![2024-09-22_21 48 47](https://github.com/user-attachments/assets/54ee9e41-bade-46f6-8349-99ec1be68e37)
can't interact with empty hand

and, when stealing the train schedule, the warning will also pop, but will not protect the schedule

**Comment by HLHTHoldWind** [comment]
You need to spam click like 4~5 times to give the conductor schedule

But only one click can steal the schedule

**Comment by HLHTHoldWind** [comment]
> @HLHTHoldWind Did you try interacting with other mobs with an empty hand? Conductors are just normal mobs, protected the same way as everything else. There is no reason for them to work differently. Did you actually test after I asked you?

I find also another interact method maybe similar with the schedule given or stolen - "Repair the iron golem using the iron ingot"
use the iron ingot to repair the golem will also bypass the entity protection, probably the similar reason why I can steal the schedule

**Comment by thexaero** [comment]
@HLHTHoldWind Did you actually test armor stands? This won't make sense unless those are also not protected.

**Comment by HLHTHoldWind** [comment]
> @HLHTHoldWind Did you actually test armor stands? This won't make sense unless those are also not protected.

![2024-09-22_22 00 58](https://github.com/user-attachments/assets/815e8941-3895-462f-9586-499f4d2a956d)
The armor stand

**Comment by thexaero** [comment]
@HLHTHoldWind Try taking something off it, e.g. a helmet.

**Comment by HLHTHoldWind** [comment]
![2024-09-22_22 02 25](https://github.com/user-attachments/assets/1edbf475-e4e2-4471-a3cc-9c0dd03dfffb)
![2024-09-22_22 02 15](https://github.com/user-attachments/assets/668b5f79-e0c8-4de6-868b-36810ea3f71d)
I can't either take or put a helmet on it

**Comment by HLHTHoldWind** [comment]
Maybe the schedule is apply to the train instead of change the state of the conductor?

**Comment by HLHTHoldWind** [comment]
As I know, the train will automatically give the new conductor a schedule when there's a schedule on the train before (like the old conductor has been killed)
Probably the schedule editing is apply to the train by create mod itself, instead of the change made by player

**Comment by thexaero** [comment]
@HLHTHoldWind Are you also using Arclight on the server?

**Comment by HLHTHoldWind** [comment]
> @HLHTHoldWind Are you also using Arclight on the server?

What's Arclight? I can't find this mod on modrinth

**Comment by thexaero** [comment]
@HLHTHoldWind Can you find it on your server? I think it's a mod that would let you use bukkit/spigot plugins on Fabric. That's what caused the issue originally.

**Comment by HLHTHoldWind** [comment]
> @HLHTHoldWind Can you find it on your server? I think it's a mod that would let you use bukkit/spigot plugins on Fabric. That's what caused the issue originally.

No, there's no mod like this on my server. All mods on my server are pure fabric

**Comment by HLHTHoldWind** [comment]
> @HLHTHoldWind Can you find it on your server? I think it's a mod that would let you use bukkit/spigot plugins on Fabric. That's what caused the issue originally.

I create a new server to test this issue.
Even if I only install these basic mods, the issue will still happen
![image](https://github.com/user-attachments/assets/c39a98ff-071d-4139-b327-d4053ac0b9a2)

**Comment by thexaero** [comment]
@HLHTHoldWind Gotcha. Probably something changed on Fabric API's or Create's end that I need to adapt to. Thanks for all the info! I'll investigate this further.

**Comment by thexaero** [comment]
Fixed.
